import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <Link className="Link" href="/">
              {" "}
              <h1>Flightracker</h1>
            </Link>
              <div>
                 <SignedOut>
              <SignInButton />
              
           
           
            </SignedOut>
              </div>
            
     
      
       
            
          </header>
        
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
